### ISSUE TITLE
Configurar o phpcs com um xml de regras já definido

### ISSUE THREAD

**Issue by dcorrea777** [autodocdev/slim-skeleton-api#1]

**Comment by diegorondao** [comment]
Estou iniciando esta atividade.

**Comment by diegorondao** [comment]
Esse recurso já foi inserido no projeto. 
Realizei os testes e o mesmo aplica as regras corretamente.

![image](https://user-images.githubusercontent.com/13041373/171173005-8a2995f3-194f-4058-90b8-5f7866acae23.png)
